/-
Copyright (c) 2026 The STFspec Contributors. Licensed under Apache-2.0 OR MIT.
-/

import STFSpec.Hash.KeccakPermutation

/-!
# Packed Keccak-f[1600] candidate

Library `EthHash`. `State` stores 25 native UInt64 fields, grouped by y rows.
Field `aXY` denotes coordinate (x,y), at reference index x+5*y. Each step reads
its input state and constructs a new state; chi therefore retains the original
row. `toReference` is the public observer; it is used in laws and conversions,
not in the packed permutation hot path. The current public hash defaults remain
in the retained reference modules; this candidate makes no D4 status change.

Generated by `scripts/gen_packed_keccak.py`; edit the generator and regenerate.
The algorithm is FIPS 202 §§3.1–3.4 (https://doi.org/10.6028/NIST.FIPS.202), also
underlying pinned pycryptodome 3.23.0 behind EELS `src/ethereum/crypto/hash.py:62`.
EELS has no raw permutation API; these are ordinary reference equations.
Spec guidance: `STFSpec/informal/modules/EthHash.md` §§3,6,7.
-/

namespace STFSpec.Hash.PackedKeccak

/-- Native 25-lane state. `aXY` is coordinate (x,y); fields are internal by convention. -/
structure State where
  -- Row y = 0.
  a00 : UInt64
  a10 : UInt64
  a20 : UInt64
  a30 : UInt64
  a40 : UInt64
  -- Row y = 1.
  a01 : UInt64
  a11 : UInt64
  a21 : UInt64
  a31 : UInt64
  a41 : UInt64
  -- Row y = 2.
  a02 : UInt64
  a12 : UInt64
  a22 : UInt64
  a32 : UInt64
  a42 : UInt64
  -- Row y = 3.
  a03 : UInt64
  a13 : UInt64
  a23 : UInt64
  a33 : UInt64
  a43 : UInt64
  -- Row y = 4.
  a04 : UInt64
  a14 : UInt64
  a24 : UInt64
  a34 : UInt64
  a44 : UInt64

/-- Read one lane by its bounded reference index without constructing an array. -/
def lane (s : State) (i : Fin 25) : UInt64 :=
  match i.val with
  | 0 => s.a00
  | 1 => s.a10
  | 2 => s.a20
  | 3 => s.a30
  | 4 => s.a40
  | 5 => s.a01
  | 6 => s.a11
  | 7 => s.a21
  | 8 => s.a31
  | 9 => s.a41
  | 10 => s.a02
  | 11 => s.a12
  | 12 => s.a22
  | 13 => s.a32
  | 14 => s.a42
  | 15 => s.a03
  | 16 => s.a13
  | 17 => s.a23
  | 18 => s.a33
  | 19 => s.a43
  | 20 => s.a04
  | 21 => s.a14
  | 22 => s.a24
  | 23 => s.a34
  | _ => s.a44

/-- Observe native fields through the public reference coordinate constructor. -/
def toReference (s : State) : KeccakState :=
  keccakOfLanes fun x y ↦ lane s (keccakLaneIndex x y)

/-- Pack a reference state once at an explicit representation boundary. -/
def ofReference (a : KeccakState) : State := ⟨keccakLane a 0 0, keccakLane a 1 0,
   keccakLane a 2 0, keccakLane a 3 0,
   keccakLane a 4 0,
   keccakLane a 0 1, keccakLane a 1 1,
   keccakLane a 2 1, keccakLane a 3 1,
   keccakLane a 4 1,
   keccakLane a 0 2, keccakLane a 1 2,
   keccakLane a 2 2, keccakLane a 3 2,
   keccakLane a 4 2,
   keccakLane a 0 3, keccakLane a 1 3,
   keccakLane a 2 3, keccakLane a 3 3,
   keccakLane a 4 3,
   keccakLane a 0 4, keccakLane a 1 4,
   keccakLane a 2 4, keccakLane a 3 4,
   keccakLane a 4 4⟩

/-- Packing the public reference observation reconstructs the packed state. -/
theorem ofReference_toReference (s : State) : ofReference (toReference s) = s := by
  cases s
  simp only [ofReference, toReference, keccakLane_ofLanes]
  rfl

/-- The reference observer determines the packed state. -/
theorem toReference_injective : Function.Injective toReference := by
  intro a b h
  simpa only [ofReference_toReference] using congrArg ofReference h

/-- Observing an explicitly packed reference state preserves every lane. -/
theorem toReference_ofReference (a : KeccakState) : toReference (ofReference a) = a := by
  apply keccakToModel_inj
  funext p
  rcases p with ⟨⟨x, hx⟩, ⟨y, hy⟩⟩
  have hxc : x = 0 ∨ x = 1 ∨ x = 2 ∨ x = 3 ∨ x = 4 := by omega
  have hyc : y = 0 ∨ y = 1 ∨ y = 2 ∨ y = 3 ∨ y = 4 := by omega
  rcases hxc with rfl | rfl | rfl | rfl | rfl <;>
    rcases hyc with rfl | rfl | rfl | rfl | rfl <;>
    simp only [keccakToModel, toReference, ofReference, keccakLane_ofLanes] <;> rfl

/-- The packed indexed lane agrees with the public reference coordinate observation. -/
theorem toReference_lane (s : State) (x y : Fin 5) :
    keccakLane (toReference s) x y = lane s (keccakLaneIndex x y) := by
  rw [toReference, keccakLane_ofLanes]

/-- Theta caches five column parities and corrections before updating all rows. -/
def theta (s : State) : State :=
  let c0 := s.a00 ^^^ s.a01 ^^^ s.a02 ^^^ s.a03 ^^^ s.a04
  let c1 := s.a10 ^^^ s.a11 ^^^ s.a12 ^^^ s.a13 ^^^ s.a14
  let c2 := s.a20 ^^^ s.a21 ^^^ s.a22 ^^^ s.a23 ^^^ s.a24
  let c3 := s.a30 ^^^ s.a31 ^^^ s.a32 ^^^ s.a33 ^^^ s.a34
  let c4 := s.a40 ^^^ s.a41 ^^^ s.a42 ^^^ s.a43 ^^^ s.a44
  let d0 := c4 ^^^ keccakRotl c1 1
  let d1 := c0 ^^^ keccakRotl c2 1
  let d2 := c1 ^^^ keccakRotl c3 1
  let d3 := c2 ^^^ keccakRotl c4 1
  let d4 := c3 ^^^ keccakRotl c0 1
  ⟨s.a00 ^^^ d0, s.a10 ^^^ d1,
   s.a20 ^^^ d2, s.a30 ^^^ d3,
   s.a40 ^^^ d4,
   s.a01 ^^^ d0, s.a11 ^^^ d1,
   s.a21 ^^^ d2, s.a31 ^^^ d3,
   s.a41 ^^^ d4,
   s.a02 ^^^ d0, s.a12 ^^^ d1,
   s.a22 ^^^ d2, s.a32 ^^^ d3,
   s.a42 ^^^ d4,
   s.a03 ^^^ d0, s.a13 ^^^ d1,
   s.a23 ^^^ d2, s.a33 ^^^ d3,
   s.a43 ^^^ d4,
   s.a04 ^^^ d0, s.a14 ^^^ d1,
   s.a24 ^^^ d2, s.a34 ^^^ d3,
   s.a44 ^^^ d4⟩

/-- Rho rotates each lane by its fixed FIPS 202 offset in x+5*y order. -/
def rho (s : State) : State :=
  ⟨keccakRotl s.a00 0, keccakRotl s.a10 1,
   keccakRotl s.a20 62, keccakRotl s.a30 28,
   keccakRotl s.a40 27,
   keccakRotl s.a01 36, keccakRotl s.a11 44,
   keccakRotl s.a21 6, keccakRotl s.a31 55,
   keccakRotl s.a41 20,
   keccakRotl s.a02 3, keccakRotl s.a12 10,
   keccakRotl s.a22 43, keccakRotl s.a32 25,
   keccakRotl s.a42 39,
   keccakRotl s.a03 41, keccakRotl s.a13 45,
   keccakRotl s.a23 15, keccakRotl s.a33 21,
   keccakRotl s.a43 8,
   keccakRotl s.a04 18, keccakRotl s.a14 2,
   keccakRotl s.a24 61, keccakRotl s.a34 56,
   keccakRotl s.a44 14⟩

/-- Pi output (x,y) reads original coordinate ((x+3*y) mod 5,x). -/
def pi (s : State) : State :=
  ⟨s.a00, s.a11,
   s.a22, s.a33,
   s.a44,
   s.a30, s.a41,
   s.a02, s.a13,
   s.a24,
   s.a10, s.a21,
   s.a32, s.a43,
   s.a04,
   s.a40, s.a01,
   s.a12, s.a23,
   s.a34,
   s.a20, s.a31,
   s.a42, s.a03,
   s.a14⟩

/-- Chi reads all three operands from the original row, preserving simultaneous updates. -/
def chi (s : State) : State :=
  ⟨s.a00 ^^^ ((~~~s.a10) &&& s.a20), s.a10 ^^^ ((~~~s.a20) &&& s.a30),
   s.a20 ^^^ ((~~~s.a30) &&& s.a40), s.a30 ^^^ ((~~~s.a40) &&& s.a00),
   s.a40 ^^^ ((~~~s.a00) &&& s.a10),
   s.a01 ^^^ ((~~~s.a11) &&& s.a21), s.a11 ^^^ ((~~~s.a21) &&& s.a31),
   s.a21 ^^^ ((~~~s.a31) &&& s.a41), s.a31 ^^^ ((~~~s.a41) &&& s.a01),
   s.a41 ^^^ ((~~~s.a01) &&& s.a11),
   s.a02 ^^^ ((~~~s.a12) &&& s.a22), s.a12 ^^^ ((~~~s.a22) &&& s.a32),
   s.a22 ^^^ ((~~~s.a32) &&& s.a42), s.a32 ^^^ ((~~~s.a42) &&& s.a02),
   s.a42 ^^^ ((~~~s.a02) &&& s.a12),
   s.a03 ^^^ ((~~~s.a13) &&& s.a23), s.a13 ^^^ ((~~~s.a23) &&& s.a33),
   s.a23 ^^^ ((~~~s.a33) &&& s.a43), s.a33 ^^^ ((~~~s.a43) &&& s.a03),
   s.a43 ^^^ ((~~~s.a03) &&& s.a13),
   s.a04 ^^^ ((~~~s.a14) &&& s.a24), s.a14 ^^^ ((~~~s.a24) &&& s.a34),
   s.a24 ^^^ ((~~~s.a34) &&& s.a44), s.a34 ^^^ ((~~~s.a44) &&& s.a04),
   s.a44 ^^^ ((~~~s.a04) &&& s.a14)⟩

/-- Iota XORs the selected round constant into (0,0) and preserves other lanes. -/
def iota (s : State) (r : Fin 24) : State :=
  { s with a00 := s.a00 ^^^ keccakRoundConstants[r] }

/-- One round applies theta, rho, pi, chi and iota in that order. -/
def round (s : State) (r : Fin 24) : State := iota (chi (pi (rho (theta s)))) r

/-- The first n bounded rounds, in ascending constant order. -/
def rounds (s : State) : (n : Nat) → n ≤ 24 → State
  | 0, _ => s
  | n + 1, h => round (rounds s n (by omega)) ⟨n, by omega⟩

/-- The complete 24-round packed Keccak-f[1600] permutation. -/
def permutation (s : State) : State := rounds s 24 (by decide)

/-- Packed theta commutes with the retained reference step. -/
theorem toReference_theta (s : State) : toReference (theta s) = keccakTheta (toReference s) := by
  apply keccakToModel_inj
  funext p
  rcases p with ⟨⟨x, hx⟩, ⟨y, hy⟩⟩
  have hxc : x = 0 ∨ x = 1 ∨ x = 2 ∨ x = 3 ∨ x = 4 := by omega
  have hyc : y = 0 ∨ y = 1 ∨ y = 2 ∨ y = 3 ∨ y = 4 := by omega
  rcases hxc with rfl | rfl | rfl | rfl | rfl <;>
    rcases hyc with rfl | rfl | rfl | rfl | rfl <;>
    simp only [keccakToModel, toReference, keccakTheta, keccakLane_ofLanes] <;>
    rfl

/-- Packed rho commutes with the retained reference step. -/
theorem toReference_rho (s : State) : toReference (rho s) = keccakRho (toReference s) := by
  apply keccakToModel_inj
  funext p
  rcases p with ⟨⟨x, hx⟩, ⟨y, hy⟩⟩
  have hxc : x = 0 ∨ x = 1 ∨ x = 2 ∨ x = 3 ∨ x = 4 := by omega
  have hyc : y = 0 ∨ y = 1 ∨ y = 2 ∨ y = 3 ∨ y = 4 := by omega
  rcases hxc with rfl | rfl | rfl | rfl | rfl <;>
    rcases hyc with rfl | rfl | rfl | rfl | rfl <;>
    simp only [keccakToModel, toReference, keccakRho, keccakLane_ofLanes] <;>
    rfl

/-- Packed pi commutes with the retained reference step. -/
theorem toReference_pi (s : State) : toReference (pi s) = keccakPi (toReference s) := by
  apply keccakToModel_inj
  funext p
  rcases p with ⟨⟨x, hx⟩, ⟨y, hy⟩⟩
  have hxc : x = 0 ∨ x = 1 ∨ x = 2 ∨ x = 3 ∨ x = 4 := by omega
  have hyc : y = 0 ∨ y = 1 ∨ y = 2 ∨ y = 3 ∨ y = 4 := by omega
  rcases hxc with rfl | rfl | rfl | rfl | rfl <;>
    rcases hyc with rfl | rfl | rfl | rfl | rfl <;>
    simp only [keccakToModel, toReference, keccakPi, keccakLane_ofLanes] <;>
    simp [pi, lane, keccakLaneIndex, keccakCoord] <;> rfl

/-- Packed chi commutes with the retained reference step. -/
theorem toReference_chi (s : State) : toReference (chi s) = keccakChi (toReference s) := by
  apply keccakToModel_inj
  funext p
  rcases p with ⟨⟨x, hx⟩, ⟨y, hy⟩⟩
  have hxc : x = 0 ∨ x = 1 ∨ x = 2 ∨ x = 3 ∨ x = 4 := by omega
  have hyc : y = 0 ∨ y = 1 ∨ y = 2 ∨ y = 3 ∨ y = 4 := by omega
  rcases hxc with rfl | rfl | rfl | rfl | rfl <;>
    rcases hyc with rfl | rfl | rfl | rfl | rfl <;>
    simp only [keccakToModel, toReference, keccakChi, keccakLane_ofLanes] <;>
    simp [chi, lane, keccakLaneIndex, keccakCoord] <;> rfl

/-- Packed iota commutes with the retained reference step. -/
theorem toReference_iota (s : State) (r : Fin 24) :
    toReference (iota s r) = keccakIota (toReference s) r := by
  apply keccakToModel_inj
  funext p
  rcases p with ⟨⟨x, hx⟩, ⟨y, hy⟩⟩
  have hxc : x = 0 ∨ x = 1 ∨ x = 2 ∨ x = 3 ∨ x = 4 := by omega
  have hyc : y = 0 ∨ y = 1 ∨ y = 2 ∨ y = 3 ∨ y = 4 := by omega
  rcases hxc with rfl | rfl | rfl | rfl | rfl <;>
    rcases hyc with rfl | rfl | rfl | rfl | rfl <;>
    simp only [keccakToModel, toReference, keccakIota, keccakLane_ofLanes] <;>
    rfl

/-- One packed round commutes with its retained reference round. -/
theorem toReference_round (s : State) (r : Fin 24) :
    toReference (round s r) = keccakRound (toReference s) r := by
  simp only [round, keccakRound, toReference_iota, toReference_chi, toReference_pi,
    toReference_rho, toReference_theta]

/-- Every bounded round prefix commutes with the reference prefix. -/
theorem toReference_rounds (s : State) (n : Nat) (h : n ≤ 24) :
    toReference (rounds s n h) = keccakRounds (toReference s) n h := by
  induction n with
  | zero => rfl
  | succ n ih => rw [rounds, toReference_round, ih, keccakRounds]

/-- The complete packed permutation commutes with the reference. -/
theorem toReference_permutation (s : State) :
    toReference (permutation s) = keccakF1600 (toReference s) :=
  toReference_rounds s 24 (by decide)

/-- Observe the packed state in the public BitVec-coordinate semantic model. -/
def toModel (s : State) : KeccakModel := keccakToModel (toReference s)

/-- The semantic model observer is injective. -/
theorem toModel_injective : Function.Injective toModel := by
  intro a b h
  apply toReference_injective
  exact keccakToModel_inj h

/-- Packed theta commutes with the public coordinate model. -/
theorem toModel_theta (s : State) :
    toModel (theta s) = KeccakModel.theta (toModel s) := by
  rw [toModel, toReference_theta, keccakToModel_theta]
  rfl

/-- Packed rho commutes with the public coordinate model. -/
theorem toModel_rho (s : State) :
    toModel (rho s) = KeccakModel.rho (toModel s) := by
  rw [toModel, toReference_rho, keccakToModel_rho]
  rfl

/-- Packed pi commutes with the public coordinate model. -/
theorem toModel_pi (s : State) :
    toModel (pi s) = KeccakModel.pi (toModel s) := by
  rw [toModel, toReference_pi, keccakToModel_pi]
  rfl

/-- Packed chi commutes with the public coordinate model. -/
theorem toModel_chi (s : State) :
    toModel (chi s) = KeccakModel.chi (toModel s) := by
  rw [toModel, toReference_chi, keccakToModel_chi]
  rfl

/-- Packed iota commutes with the public coordinate model. -/
theorem toModel_iota (s : State) (r : Fin 24) :
    toModel (iota s r) = KeccakModel.iota (toModel s) r := by
  rw [toModel, toReference_iota, keccakToModel_iota]
  rfl

/-- Packed round commutes with the public coordinate model. -/
theorem toModel_round (s : State) (r : Fin 24) :
    toModel (round s r) = KeccakModel.round (toModel s) r := by
  rw [toModel, toReference_round, keccakToModel_round]
  rfl

/-- Every bounded packed round prefix commutes with the coordinate model. -/
theorem toModel_rounds (s : State) (n : Nat) (h : n ≤ 24) :
    toModel (rounds s n h) = KeccakModel.rounds (toModel s) n h := by
  rw [toModel, toReference_rounds, keccakToModel_rounds]
  rfl

/-- The packed permutation commutes with the public coordinate model. -/
theorem toModel_permutation (s : State) :
    toModel (permutation s) = KeccakModel.rounds (toModel s) 24 (by decide) := by
  rw [toModel, toReference_permutation, keccakToModel_f1600]
  rfl

end STFSpec.Hash.PackedKeccak
