/-
Copyright (c) 2026 The STFspec Contributors. Licensed under Apache-2.0 OR MIT.
-/

import STFSpec.Hash.Blake2Compression

/-!
# BLAKE2b compression guards

Library `EthConformance`. Primary EIP-152 test vectors 4–7:
https://eips.ethereum.org/EIPS/eip-152#test-vector-4 (through test-vector-7).
Test vector 8 remains PARSE-ONLY in `Blake2ParametersGuards`; no maximum-count
compression runs here. Expected byte observations are the selected primary facts,
not output generated by the reference. The differential suite supplies separate
pinned G/compression, alias, high-bit, sigma wrap and independent-integer checks.
Spec guidance: `STFSpec/informal/modules/EthHash.md` §§3–4.
-/

namespace STFSpec.Conformance.Hash.Blake2CompressionGuards
open STFSpec.Hash.Blake2b

private def primaryH : Vector UInt64 8 := #v[7640891576939301192,13503953896175478587,4354685564936845355,11912009170470909681,5840696475078001361,11170449401992604703,2270897969802886507,6620516959819538809]
private def primaryM : Vector UInt64 16 := #v[6513249,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]

-- Primary EIP-152 test-vector-4.
#guard (compress 0 primaryH primaryM 3 0 true).data =
  #[8,201,188,243,103,230,9,106,59,167,202,132,133,174,103,187,43,248,148,254,114,243,110,60,241,54,29,95,58,245,79,165,210,130,230,173,127,82,14,81,31,108,62,43,140,104,5,155,148,66,190,4,84,38,124,224,121,33,126,19,25,205,224,91]

-- Primary EIP-152 test-vector-5.
#guard (compress 12 primaryH primaryM 3 0 true).data =
  #[186,128,165,63,152,28,77,13,106,39,151,182,159,18,246,233,76,33,47,20,104,90,196,183,75,18,187,111,219,255,162,209,125,135,197,57,42,171,121,45,194,82,213,222,69,51,204,149,24,211,138,168,219,241,146,90,185,35,134,237,212,0,153,35]

-- Primary EIP-152 test-vector-6.
#guard (compress 12 primaryH primaryM 3 0 false).data =
  #[117,171,105,211,25,10,86,44,81,174,248,216,143,28,39,117,135,105,68,64,114,112,196,44,152,68,37,44,38,210,135,82,152,116,62,127,109,94,162,242,211,232,210,38,3,156,211,27,78,66,106,196,242,211,214,102,166,16,194,17,111,222,71,53]

-- Primary EIP-152 test-vector-7.
#guard (compress 1 primaryH primaryM 3 0 true).data =
  #[182,58,56,12,178,137,125,82,25,148,168,82,52,238,44,24,27,95,132,77,44,98,76,0,38,119,233,112,52,73,210,251,165,81,179,168,51,59,205,245,242,247,224,137,147,213,57,35,222,61,100,252,198,140,3,78,113,123,146,147,254,215,164,33]

#guard rotr 0x8000000000000001 32 = 0x0000000180000000
#guard rotr 0x8000000000000001 24 = 0x0000018000000000
#guard rotr 0x8000000000000001 16 = 0x0001800000000000
#guard rotr 0x8000000000000001 63 = 3
#guard rotr 0x8000000000000001 0 = 0x8000000000000001
#guard rotr 0x8000000000000001 64 = 0x8000000000000001
#guard rotr 0x8000000000000001 129 = 0xc000000000000000

-- Fixed-width zero output and little-endian/high-bit byte positions.
#guard (serializeWords (Vector.replicate 8 0)).data = Array.replicate 64 0
#guard (serializeWords #v[0x8000000000000001,0,0,0,0,0,0,0]).data =
  #[1,0,0,0,0,0,0,128] ++ Array.replicate 56 0

-- High-bit counters and flag changes are observed before round zero.
#guard (initState primaryH 0x8000000000000000 0xffffffffffffffff false)[12] =
  0xd10e527fade682d1
#guard (initState primaryH 0x8000000000000000 0xffffffffffffffff true)[13] =
  0x64fa9773d4c193e0
#guard (initState primaryH 0 0 true)[14] = 0xe07c265404be4294
#guard (initState primaryH 0 0 false)[14] = 0x1f83d9abfb41bd6b

end STFSpec.Conformance.Hash.Blake2CompressionGuards
