#!/usr/bin/env python3
# Copyright (c) 2026 The STFspec Contributors. Licensed under Apache-2.0 OR MIT.
"""Generate STFSpec/informal/GAPS.md: the repository-wide register of everything missing.

It concatenates STFSpec/informal/GAPS-CROSSCUTTING.md (gaps no single module owns, maintained by hand)
with the "## 10. Gaps" section of every spec guidance document, in dependency order, plus the list of
EELS inventory items still neither claimed nor excluded (from scripts/check_spec.py).
`--check` fails if STFSpec/informal/GAPS.md is stale. Any check_spec failure aborts generation
without overwriting the existing register; fix the reported invalid specification first.
"""
import pathlib, posixpath, re, subprocess, sys, tomllib

ROOT = pathlib.Path(__file__).resolve().parent.parent

def rebase_module_links(body: str) -> str:
    """Module gaps move up one directory when copied into STFSpec/informal/GAPS.md."""
    def replace(match):
        target = match[2]
        if target.startswith(("#", "/")) or re.match(r"[a-zA-Z][a-zA-Z0-9+.-]*:", target):
            return match[0]
        path, separator, anchor = target.partition("#")
        return match[1] + posixpath.normpath("modules/" + path) + separator + anchor + match[3]
    return re.sub(r"(\[[^\]\n]+\]\()([^\s)]+)(\))", replace, body)

def order():
    b = tomllib.loads((ROOT / "scripts/boundaries.toml").read_text())["libs"]
    seen, out = set(), []
    def visit(l):
        if l in seen: return
        seen.add(l)
        for d in b[l]["deps"]: visit(d)
        out.append(l)
    for l in b: visit(l)
    proofs = [l["name"] for pkg in ("STFSpecMathlib", "STFSpecSecurity")
              for l in tomllib.loads((ROOT / pkg / "lakefile.toml").read_text()).get("lean_lib", [])]
    return out + proofs

def build() -> str:
    cc_text = (ROOT / "STFSpec/informal/GAPS-CROSSCUTTING.md").read_text()
    source_date = re.search(r"Date: (\d{4}-\d{2}-\d{2})", cc_text)[1]
    parts = ["# Gap register\n",
             f"*Status: generated gap register. Source date: {source_date}.*\n",
             "*Generated by `scripts/gen_gaps.py` from `STFSpec/informal/GAPS-CROSSCUTTING.md` and the §10 Gaps section of each "
             "spec guidance document. Do not edit by hand: fix the source section, then regenerate.*\n"]
    cc = ROOT / "STFSpec/informal/GAPS-CROSSCUTTING.md"
    if cc.exists():
        parts.append(cc.read_text().rstrip() + "\n")
    parts.append("## Unclaimed EELS inventory items\n")
    r = subprocess.run([sys.executable, str(ROOT / "scripts/check_spec.py"), "--report"], capture_output=True, text=True)
    if r.returncode:
        raise RuntimeError("cannot generate a validated gap register while check_spec fails:\n" + r.stdout + r.stderr)
    un = [l.removeprefix("spec: unclaimed: ") for l in r.stdout.splitlines() if l.startswith("spec: unclaimed:")]
    parts.append("\n".join(f"- {u}" for u in un) + "\n" if un else "None: every inventory item is claimed by a module or excluded with a reason.\n")
    parts.append("## Per-module gaps\n")
    for lib in order():
        p = ROOT / "STFSpec/informal/modules" / f"{lib}.md"
        if not p.exists():
            parts.append(f"### `{lib}`\n\n**Spec guidance missing.**\n"); continue
        t = p.read_text()
        sec = t.split("## 10. Gaps", 1)[1] if "## 10. Gaps" in t else "\n**No Gaps section.**\n"
        body = sec.strip().replace("\n### ", "\n#### ").replace("\n## ", "\n#### ")
        parts.append(f"### [`{lib}`](modules/{lib}.md)\n\n{rebase_module_links(body)}\n")
    return "\n".join(parts)

def main() -> int:
    out = ROOT / "STFSpec/informal/GAPS.md"
    try:
        new = build()
    except RuntimeError as e:
        print(e)
        return 1
    if "--check" in sys.argv:
        if not out.exists() or out.read_text() != new:
            print("STFSpec/informal/GAPS.md is stale: run scripts/gen_gaps.py"); return 1
        print("STFSpec/informal/GAPS.md up to date"); return 0
    out.write_text(new); print(f"STFSpec/informal/GAPS.md regenerated ({new.count(chr(10))} lines)"); return 0

if __name__ == "__main__":
    sys.exit(main())
