#!/usr/bin/env python3
# Copyright (c) 2026 The STFspec Contributors. Licensed under Apache-2.0 OR MIT.
"""Extract annotated reference records, including wire field order, from pinned EELS.

Usage: gen_reference_records.py EELS_CHECKOUT [--check]
This supplements module signatures; it does not prescribe the Lean representation.
"""
import argparse
import ast
import collections
import json
import pathlib
import subprocess
import tomllib

from check_spec import CLAIM

ROOT = pathlib.Path(__file__).resolve().parent.parent


def render(eels):
    pin = tomllib.loads((ROOT / "reference.toml").read_text())["release"]
    head = subprocess.check_output(["git", "rev-parse", "HEAD"], cwd=eels, text=True).strip()
    if head != pin["commit"]:
        raise ValueError("checkout does not match the pinned reference (reference.toml)")
    if subprocess.check_output(["git", "status", "--porcelain", "--", "src", "uv.lock"], cwd=eels):
        raise ValueError("checkout source or lock has local changes")
    inventory = json.loads((ROOT / "STFSpec/informal/eels-inventory.json").read_text())
    if inventory["release"] != pin["commit"]:
        raise ValueError("inventory does not match the pinned reference (reference.toml)")
    owners = {}
    for spec in sorted((ROOT / "STFSpec/informal/modules").glob("*.md")):
        source_map = spec.read_text().split("## 3. EELS source map", 1)[1].split("## 4. Tests", 1)[0]
        for path, name in CLAIM.findall(source_map):
            owners[(path, name)] = spec.stem
    records = collections.defaultdict(list)
    for file in sorted({item["file"] for item in inventory["items"] if item["kind"] == "class"}):
        tree = ast.parse((eels / "src/ethereum" / file).read_text())
        for cls in tree.body:
            if not isinstance(cls, ast.ClassDef):
                continue
            owner = owners.get((file, cls.name), owners.get((file, "*")))
            fields = [node for node in cls.body if isinstance(node, ast.AnnAssign)
                      and isinstance(node.target, ast.Name)]
            if not owner or not fields:
                continue
            records[owner].append((file, cls, fields))
    chunks = ["# Reference record fields\n\n",
              "*Generated by `scripts/gen_reference_records.py`; do not edit by hand.*\n\n",
              f"*Status: generated source snapshot. Source date: {pin['published'][:10]}.*\n\n",
              f"Pin: `{pin['tag']}` @`{pin['commit']}`.\n\n",
              "These tables list annotated fields in source order, with the exact Python type expressions. "
              "For RLP dataclasses and SSZ containers, field order and annotations are normative. "
              "Resolve annotation constants from the module requirements/source map. "
              "Base classes are listed separately: inherited fields must also be accounted for. "
              "Runtime records describe reference state, including caches; the module's model and "
              "public interface determine the Lean representation. A source item's owner can differ "
              "from the common type's owner (for example Log under D27). "
              "Other annotated classes also include class constants, not just instance fields. "
              "Read this file with [COMPOSITION.md](COMPOSITION.md) and the relevant module §5.\n\n"]
    for owner, entries in sorted(records.items()):
        chunks += [f"## {owner}\n\n"]
        for file, cls, fields in entries:
            bases = ", ".join(f"`{ast.unparse(base)}`" for base in cls.bases) or "none"
            form = "dataclass" if any(isinstance(decorator, ast.Name) and decorator.id == "dataclass"
                                       for decorator in cls.decorator_list) else "annotated class (may include class constants)"
            chunks += [f"### {cls.name}\n\n",
                       f"Source: `{file}:{cls.lineno}`. Bases: {bases}. Form: {form}.\n\n",
                       "| Position | Python field | Lean spelling | Python annotation |\n"
                       "|---|---|---|---|\n"]
            for index, node in enumerate(fields):
                name = node.target.id
                pieces = name.split("_")
                camel = pieces[0] + "".join(piece[:1].upper() + piece[1:] for piece in pieces[1:])
                annotation = ast.unparse(node.annotation).replace("|", "\\|")
                chunks += [f"| {index} | `{name}` | `{camel}` | `{annotation}` |\n"]
            chunks += ["\n"]
    return "".join(chunks)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("eels", type=pathlib.Path)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    try:
        document = render(args.eels.resolve())
    except (ValueError, subprocess.CalledProcessError) as error:
        parser.error(str(error))
    target = ROOT / "STFSpec/informal/REFERENCE-RECORDS.md"
    if args.check:
        if not target.exists() or target.read_text() != document:
            print("STFSpec/informal/REFERENCE-RECORDS.md is stale; regenerate from the pinned EELS checkout")
            return 1
        print("reference record fields match the pinned source")
    else:
        target.write_text(document)
        print(f"reference record fields generated ({document.count(chr(10))} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
