#!/usr/bin/env python3
# Copyright (c) 2026 The STFspec Contributors. Licensed under Apache-2.0 OR MIT.
"""Generate the packed Keccak permutation and ordinary finite-coordinate proofs.

Run from any directory; --check verifies the retained production source.
The generator uses x+5*y coordinates, the FIPS 202 rho table, and explicit
expressions matching the retained reference. All emitted laws are kernel checked.
Spec guidance: STFSpec/informal/modules/EthHash.md §§3,6,7.
"""
from pathlib import Path
import argparse
import re

lanes=list(range(25))
field=lambda i:f'a{i%5}{i//5}'
read=lambda i:f's.{field(i)}'
def rec(expressions):
    rows=[]
    for y in range(0,25,5):
        chunk=expressions[y:y+5]
        rows.append(',\n   '.join(', '.join(chunk[j:j+2]) for j in range(0,5,2)))
    return '⟨' + ',\n   '.join(rows) + '⟩'
offset=[0,1,62,28,27,36,44,6,55,20,3,10,43,25,39,41,45,15,21,8,18,2,61,56,14]
s='''/-
Copyright (c) 2026 The STFspec Contributors. Licensed under Apache-2.0 OR MIT.
-/

import STFSpec.Hash.KeccakPermutation

/-!
# Packed Keccak-f[1600] candidate

Library `EthHash`. `State` stores 25 native UInt64 fields, grouped by y rows.
Field `aXY` denotes coordinate (x,y), at reference index x+5*y. Each step reads
its input state and constructs a new state; chi therefore retains the original
row. `toReference` is the public observer; it is used in laws and conversions,
not in the packed permutation hot path. The current public hash defaults remain
in the retained reference modules; this candidate makes no D4 status change.

Generated by `scripts/gen_packed_keccak.py`; edit the generator and regenerate.
The algorithm is FIPS 202 §§3.1–3.4 (https://doi.org/10.6028/NIST.FIPS.202), also
underlying pinned pycryptodome 3.23.0 behind EELS `src/ethereum/crypto/hash.py:62`.
EELS has no raw permutation API; these are ordinary reference equations.
Spec guidance: `STFSpec/informal/modules/EthHash.md` §§3,6,7.
-/

namespace STFSpec.Hash.PackedKeccak

/-- Native 25-lane state. `aXY` is coordinate (x,y); fields are internal by convention. -/
structure State where
'''
s+=''.join(('  -- Row y = '+str(i//5)+'.\n' if i%5==0 else '')+f'  {field(i)} : UInt64\n' for i in lanes)
s+='\ndef lane (s : State) (i : Fin 25) : UInt64 :=\n  match i.val with\n'
s+=''.join(f'  | {i} => {read(i)}\n' for i in range(24))+f'  | _ => {read(24)}\n'
s+='\ndef toReference (s : State) : KeccakState :=\n  keccakOfLanes fun x y ↦ lane s (keccakLaneIndex x y)\n'
s+='\ndef ofReference (a : KeccakState) : State := '+rec([f'keccakLane a {i%5} {i//5}' for i in lanes])+'\n'
coordinate_cases = """  apply keccakToModel_inj
  funext p
  rcases p with ⟨⟨x, hx⟩, ⟨y, hy⟩⟩
  have hxc : x = 0 ∨ x = 1 ∨ x = 2 ∨ x = 3 ∨ x = 4 := by omega
  have hyc : y = 0 ∨ y = 1 ∨ y = 2 ∨ y = 3 ∨ y = 4 := by omega
  rcases hxc with rfl | rfl | rfl | rfl | rfl <;>
    rcases hyc with rfl | rfl | rfl | rfl | rfl <;>
"""
s+='''
theorem ofReference_toReference (s : State) : ofReference (toReference s) = s := by
  cases s
  simp only [ofReference, toReference, keccakLane_ofLanes]
  rfl

theorem toReference_injective : Function.Injective toReference := by
  intro a b h
  simpa only [ofReference_toReference] using congrArg ofReference h

theorem toReference_ofReference (a : KeccakState) : toReference (ofReference a) = a := by
'''+coordinate_cases+'''    simp only [keccakToModel, toReference, ofReference, keccakLane_ofLanes] <;> rfl

theorem toReference_lane (s : State) (x y : Fin 5) :
    keccakLane (toReference s) x y = lane s (keccakLaneIndex x y) := by
  rw [toReference, keccakLane_ofLanes]

def theta (s : State) : State :=
'''
for x in range(5):s+=f'  let c{x} := '+ ' ^^^ '.join(read(x+5*y) for y in range(5))+'\n'
for x in range(5):s+=f'  let d{x} := c{(x+4)%5} ^^^ keccakRotl c{(x+1)%5} 1\n'
s+='  '+rec([read(i)+f' ^^^ d{i%5}' for i in lanes])+'\n'
s+='\ndef rho (s : State) : State :=\n  '+rec([f'keccakRotl {read(i)} {offset[i]}' for i in lanes])+'\n'
s+='\ndef pi (s : State) : State :=\n  '+rec([read((i%5+3*(i//5))%5+5*(i%5)) for i in lanes])+'\n'
s+='\ndef chi (s : State) : State :=\n  '+rec([f'{read(i)} ^^^ ((~~~{read((i%5+1)%5+5*(i//5))}) &&& {read((i%5+2)%5+5*(i//5))})' for i in lanes])+'\n'
s+='\ndef iota (s : State) (r : Fin 24) : State :=\n  { s with a00 := s.a00 ^^^ keccakRoundConstants[r] }\n'
s+='\ndef round (s : State) (r : Fin 24) : State := iota (chi (pi (rho (theta s)))) r\n'
s+='''
def rounds (s : State) : (n : Nat) → n ≤ 24 → State
  | 0, _ => s
  | n + 1, h => round (rounds s n (by omega)) ⟨n, by omega⟩

def permutation (s : State) : State := rounds s 24 (by decide)
'''
for step in ('theta','rho','pi','chi','iota'):
 args=' (r : Fin 24)' if step=='iota' else ''
 rarg=' r' if step=='iota' else ''
 extras = ', keccakCoord' if step in ('theta','pi','chi') else ', keccakRhoOffsets' if step == 'rho' else ''
 terminal = f'simp [{step}, lane, keccakLaneIndex, keccakCoord] <;> rfl' if step in ('pi', 'chi') else 'rfl'
 s+=f'''\ntheorem toReference_{step} (s : State){args} : toReference ({step} s{rarg}) = keccak{step.title()} (toReference s){rarg} := by
'''+coordinate_cases+f'''    simp only [keccakToModel, toReference, keccak{step.title()}, keccakLane_ofLanes] <;>
    {terminal}
'''
s+='''
theorem toReference_round (s : State) (r : Fin 24) :
    toReference (round s r) = keccakRound (toReference s) r := by
  simp only [round, keccakRound, toReference_iota, toReference_chi, toReference_pi, toReference_rho, toReference_theta]

theorem toReference_rounds (s : State) (n : Nat) (h : n ≤ 24) :
    toReference (rounds s n h) = keccakRounds (toReference s) n h := by
  induction n with
  | zero => rfl
  | succ n ih => rw [rounds, toReference_round, ih, keccakRounds]

theorem toReference_permutation (s : State) : toReference (permutation s) = keccakF1600 (toReference s) :=
  toReference_rounds s 24 (by decide)

/-- Observe the packed state in the public BitVec-coordinate semantic model. -/
def toModel (s : State) : KeccakModel := keccakToModel (toReference s)

/-- The semantic model observer is injective. -/
theorem toModel_injective : Function.Injective toModel := by
  intro a b h
  apply toReference_injective
  exact keccakToModel_inj h

/-- Packed theta commutes with the public coordinate model. -/
theorem toModel_theta (s : State) :
    toModel (theta s) = KeccakModel.theta (toModel s) := by
  rw [toModel, toReference_theta, keccakToModel_theta]
  rfl

/-- Packed rho commutes with the public coordinate model. -/
theorem toModel_rho (s : State) :
    toModel (rho s) = KeccakModel.rho (toModel s) := by
  rw [toModel, toReference_rho, keccakToModel_rho]
  rfl

/-- Packed pi commutes with the public coordinate model. -/
theorem toModel_pi (s : State) :
    toModel (pi s) = KeccakModel.pi (toModel s) := by
  rw [toModel, toReference_pi, keccakToModel_pi]
  rfl

/-- Packed chi commutes with the public coordinate model. -/
theorem toModel_chi (s : State) :
    toModel (chi s) = KeccakModel.chi (toModel s) := by
  rw [toModel, toReference_chi, keccakToModel_chi]
  rfl

/-- Packed iota commutes with the public coordinate model. -/
theorem toModel_iota (s : State) (r : Fin 24) :
    toModel (iota s r) = KeccakModel.iota (toModel s) r := by
  rw [toModel, toReference_iota, keccakToModel_iota]
  rfl

/-- Packed round commutes with the public coordinate model. -/
theorem toModel_round (s : State) (r : Fin 24) :
    toModel (round s r) = KeccakModel.round (toModel s) r := by
  rw [toModel, toReference_round, keccakToModel_round]
  rfl

/-- Every bounded packed round prefix commutes with the coordinate model. -/
theorem toModel_rounds (s : State) (n : Nat) (h : n ≤ 24) :
    toModel (rounds s n h) = KeccakModel.rounds (toModel s) n h := by
  rw [toModel, toReference_rounds, keccakToModel_rounds]
  rfl

/-- The packed permutation commutes with the public coordinate model. -/
theorem toModel_permutation (s : State) :
    toModel (permutation s) = KeccakModel.rounds (toModel s) 24 (by decide) := by
  rw [toModel, toReference_permutation, keccakToModel_f1600]
  rfl

end STFSpec.Hash.PackedKeccak
'''

DOCS = {
 'toReference': 'Observe native fields through the public reference coordinate constructor.',
 'ofReference': 'Pack a reference state once at an explicit representation boundary.',
 'lane': 'Read one lane by its bounded reference index without constructing an array.',
 'ofReference_toReference': 'Packing the public reference observation reconstructs the packed state.',
 'toReference_injective': 'The reference observer determines the packed state.',
 'toReference_ofReference': 'Observing an explicitly packed reference state preserves every lane.',
 'toReference_lane': 'The packed indexed lane agrees with the public reference coordinate observation.',
 'theta': 'Theta caches five column parities and corrections before updating all rows.',
 'rho': 'Rho rotates each lane by its fixed FIPS 202 offset in x+5*y order.',
 'pi': 'Pi output (x,y) reads original coordinate ((x+3*y) mod 5,x).',
 'chi': 'Chi reads all three operands from the original row, preserving simultaneous updates.',
 'iota': 'Iota XORs the selected round constant into (0,0) and preserves other lanes.',
 'round': 'One round applies theta, rho, pi, chi and iota in that order.',
 'rounds': 'The first n bounded rounds, in ascending constant order.',
 'permutation': 'The complete 24-round packed Keccak-f[1600] permutation.',
 'toReference_round': 'One packed round commutes with its retained reference round.',
 'toReference_rounds': 'Every bounded round prefix commutes with the reference prefix.',
 'toReference_permutation': 'The complete packed permutation commutes with the reference.',
}
for step in ['theta','rho','pi','chi','iota']:
    DOCS['toReference_'+step] = f'Packed {step} commutes with the retained reference step.'
s = re.sub(r'^(def|theorem) (\w+)',
           lambda m: ('/-- '+DOCS[m[2]]+' -/\n' if m[2] in DOCS else '')+m[0], s, flags=re.M)
# Break generated finite case disjunctions/tactic lists and long simp sets.
lines=[]
for line in s.splitlines():
    if len(line)<=99:
        lines.append(line);continue
    if ' ∨ ' in line:
        prefix,tail=line.split(': ',1)
        suffix=' := by omega'
        terms=tail[:-len(suffix)].split(' ∨ ')
        lines.append(prefix+': '+ ' ∨ '.join(terms[:8])+' ∨')
        for j in range(8,len(terms),8):
            lines.append('    '+' ∨ '.join(terms[j:j+8])+(' ∨' if j+8<len(terms) else suffix))
    elif 'rcases hc with' in line:
        prefix,tail=line.split(' with ',1)
        ending=' <;> simp [toReference, ofReference]' if 'simp' in tail and 'ofReference' in tail else ' <;> simp [toReference, lane] <;> rfl' if 'simp' in tail else ' <;>'
        cases=tail.split(' <;>')[0].split(' | ')
        lines.append(prefix+' with '+' | '.join(cases[:12])+' |')
        lines.extend(['    '+' | '.join(cases[12:])+' <;>', ending.replace(' <;> ', '    ', 1) if ending!=' <;>' else ''])
    elif line.startswith('theorem toReference_') and ' : ' in line:
        prefix,tail=line.rsplit(' : ',1)
        lines.extend([prefix+' :', '    '+tail])
    elif line.startswith('    simp ['):
        comma=line.rfind(', ',0,95)
        lines.extend([line[:comma+1], '      '+line[comma+2:]])
    elif line.startswith('  simp only ['):
        comma=line.rfind(', ',0,95)
        lines.extend([line[:comma+1], '    '+line[comma+2:]])
    else:lines.append(line)
s='\n'.join(lines).replace(' <;>\n\n', ' <;>\n')+'\n'
parser=argparse.ArgumentParser(description=__doc__)
parser.add_argument('--check',action='store_true')
args=parser.parse_args()
target=Path(__file__).resolve().parents[1]/'STFSpec/Hash/PackedKeccakPermutation.lean'
if args.check:
    if not target.is_file() or target.read_bytes()!=s.encode('utf-8'):
        raise SystemExit('generated packed Keccak permutation is stale')
else:
    target.write_text(s)
