#!/usr/bin/env python3
# Copyright (c) 2026 The STFspec Contributors. Licensed under Apache-2.0 OR MIT.
"""Generate the fixture area index from an authenticated pinned archive, without extraction."""
import argparse
from collections import Counter
import pathlib
import sys
import tarfile
import tomllib

from check_reference import digest


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("archive", type=pathlib.Path)
    parser.add_argument("--root", type=pathlib.Path, default=pathlib.Path(__file__).resolve().parents[1])
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    try:
        release = tomllib.loads((args.root / "reference.toml").read_text())["release"]
        fixtures = release["fixtures"]
        if args.archive.stat().st_size != fixtures["size_bytes"] or digest(args.archive) != fixtures["sha256"]:
            raise ValueError("archive fails reference.toml size/sha256 authentication")
        counts = Counter()
        with tarfile.open(args.archive, "r:gz") as archive:
            for member in archive:
                if member.isfile() and member.name.endswith(".json"):
                    name = member.name.removeprefix("./").removeprefix("fixtures/")
                    counts["/".join(name.split("/")[:4])] += 1
        if sum(counts.values()) != fixtures["json_files"]:
            raise ValueError("archive JSON file count differs from reference.toml")
        text = ("# Generated by scripts/gen_fixture_index.py; do not edit by hand.\n"
                f"# Status: pinned source snapshot. Source date: {release['published'][:10]}.\n"
                f"# EEST zkevm fixture index: {release['tag']} (sha256 in reference.toml)\n"
                "# <format>/<fork>/<source-fork>/<area>   <json files>\n")
        text += "".join(f"{area}\t{count}\n" for area, count in sorted(counts.items()))
        target = args.root / "STFSpec/informal/eest-fixture-index.txt"
        if args.check:
            if target.read_text() != text:
                raise ValueError("fixture index is stale: run scripts/gen_fixture_index.py ARCHIVE")
            print("fixture index matches the pinned archive")
        else:
            target.write_text(text)
            print(f"fixture index regenerated: {len(counts)} areas, {sum(counts.values())} JSON files")
    except (OSError, ValueError, KeyError, tarfile.TarError) as error:
        print(f"fixture index: {error}")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
